[package]
name = "rcrosshair"
version = "0.1.0"
edition = "2024"

[dependencies]
env_logger = "0.11.9"
image = { version = "0.25.9", features = ["gif"] }
log = "0.4.29"
smithay-client-toolkit = "0.20.0"
thiserror = "2.0.18"
wayland-client = "0.31.12"
